name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.5

      - name: Build debug APK
        env:
          BALE_BOT_TOKEN: ${{ secrets.BALE_BOT_TOKEN }}
          BALE_USER_ID: ${{ secrets.BALE_USER_ID }}
          BALE_CHANNEL_ID: ${{ secrets.BALE_CHANNEL_ID }}
          RUBIKA_BOT_TOKEN: ${{ secrets.RUBIKA_BOT_TOKEN }}
          RUBIKA_USER_ID: ${{ secrets.RUBIKA_USER_ID }}
          RUBIKA_CHANNEL_ID: ${{ secrets.RUBIKA_CHANNEL_ID }}
        run: gradle assembleDebug -PbaleBotToken="$BALE_BOT_TOKEN" -PbaleUserId="$BALE_USER_ID" -PbaleChannelId="$BALE_CHANNEL_ID" -PrubikaBotToken="$RUBIKA_BOT_TOKEN" -PrubikaUserId="$RUBIKA_USER_ID" -PrubikaChannelId="$RUBIKA_CHANNEL_ID"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: NotiForwarder-debug
          path: app/build/outputs/apk/debug/app-debug.apk
